# Generated by Django 5.1.4 on 2026-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('flour_grains', 'Flour & Grains'), ('dairy', 'Dairy'), ('sweeteners', 'Sweeteners'), ('flavorings', 'Flavorings & Extracts'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
