# Generated by Django 5.1.4 on 2026-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('classic', 'Classic'), ('fruity', 'Fruity'), ('local', 'Local Favorites'), ('premium', 'Premium'), ('brownies', 'Brownies & Bars')], default='classic', max_length=20),
        ),
    ]
