# Generated by Django 5.1.4 on 2026-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yield_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
